myloglink: "/TXT/mylog.txt"
githublink: "https://github.com/valeelim/os222"
author: "Valerian Salim"
title: "OS222: Operating Systems 2022-2"
tarballlink: "https://os.vlsm.org/Log/valeelim.tar.bz2.txt"
